train:
    learning_rate: 0.001
    epochs: 5
    batch_size: 32
    device: "cuda"

model:
    input_shape: [1, 640, 640]
    num_classes: 10
    batch_size: 8
    epochs: 5
    learning_rate: 0.001
